// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcbIJtsOkwMNNhKuQx7yfsOXkcgYXRufo',
    appId: '1:559629299030:android:c35053c5c0fc271e04faf7',
    messagingSenderId: '559629299030',
    projectId: 'messenger-app-30a25',
    storageBucket: 'messenger-app-30a25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7SIPcDggY6oVX5NLx_XJn96gvlkJX8AI',
    appId: '1:559629299030:ios:54ff6558cec5404c04faf7',
    messagingSenderId: '559629299030',
    projectId: 'messenger-app-30a25',
    storageBucket: 'messenger-app-30a25.appspot.com',
    iosClientId: '559629299030-86g61tdgm5bstg6v0d5m6r76pcubk8v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.messengerApp',
  );
}
